### ISSUE TITLE
[Feature Request] Items Kept and Durability Penalty Vary with Ingame Difficulty

### ISSUE THREAD

**Issue by SandwichHorror** [TheIllusiveC4/CorpseComplex#31]
**Please describe the new feature or change.**
Items Kept and Durability Penalty vary with ingame difficulty (with config to adjust the default parameters of each difficulty level)

Example:

Easy - All Items Kept - 5% durability lost on kept items
Normal - Hotbar, Armor, [Baubles - if enabled] Kept - 15% durability loss on kept items
Hard - Main and Offhand Kept, 20% durability loss on kept items

**Please describe why you want this feature.**
CorpseComplex is a fantastic tool that can make death range anywhere from essentially irrelevant to extremely punishing. I think it would be excellent for modpacks to have some built in options to make this sliding scale a little more controllable on the user end. Of all the options CC offers, these two would be some of the most direct and "easily" (I'm not a modder) scalable with difficulty.
The details of this would ideally be configurable as well.

**Comment by TheIllusiveC4** [comment]
Since you previously posted a bug about the 1.12.2 version, I'm assuming that's the version you're primarily using. Unfortunately, Corpse Complex's systems won't easily allow for this kind of configuration in 1.12.2. However, I can add this feature to the 1.14+ version which does have the ability to customize death penalties to this extent.
