### ISSUE TITLE
[BUG] Xp duplication on death, sporadically

### ISSUE THREAD

**Issue by kil0byt3** [TheIllusiveC4/CorpseComplex#33]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 1.0.10.1
* Forge: 2847
#### Observed Behavior:

Please see this issue for all info and a video: https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/36

If more info is needed, please let me know. The issue is very hard to reproduce in our testing. We are using other mods - this may be a mod incompatibility.

**Comment by TheIllusiveC4** [comment]
Hmm, if this is difficult to reproduce then this will be difficult to fix, but I'll see what I can do.

Has there been any instance of this happening outside of an enchanting context? Also, if you could produce a list of your mods installed that do anything with experience (if there are any) that would help as well.

**Comment by kil0byt3** [comment]
The only instances of this happening _seem_ to be 1. Using XP (in any way - Anvil or Enchantment table), 2. Dying, 3. You respawn with extra XP. 

We have a lot of mods that use/configure XP, enchanting, or Anvils. Here are some (I hope all, but there may be more):

[Enchanting Plus](https://www.curseforge.com/minecraft/mc-mods/enchanting-plus)
[Enchant Control](https://www.curseforge.com/minecraft/mc-mods/enchantments-control)
[Rocky Tweaks](https://www.curseforge.com/minecraft/mc-mods/rocky-tweaks)
[Quark Oddities](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Vanilla Anvil Repair](https://www.curseforge.com/minecraft/mc-mods/vanilla-anvil-repair)
I think Charm and Quark also both directly modify some enchanting procedures.

**Comment by TheIllusiveC4** [comment]
I was about to consider just rewriting some of the experience module logic to try and fix this issue since reproducing it has proven challenging, but after looking at the code and revisiting the initial issue, I'm inclined to believe this is caused by another mod entirely and there may be nothing I can do.

Part of the issue mentions that dropped experience may sometimes drop more than expected. The first and only time I set that value is [here](https://github.com/TheIllusiveC4/CorpseComplex/blob/4e96baa07e822d6c57ec1b9d4d9f8e8507875ead/src/main/java/c4/corpsecomplex/common/modules/ExperienceModule.java#L97) and that value is a pretty simple product. The video in the bug report also shows that, even though the dropped experience is more than expected, the amount does get smaller and smaller, meaning that likely the config values are working correctly to calculate diminishing returns. 

That means the issue must lie in the `player.experienceTotal` value itself being more than expected. I suspect that, since this bug only occurs with anvil and enchantment use in combination with other mods, that some mod that hooks into these mechanics is causing a desync and not actually spending the experience values server-side where all of this logic is done. And, although I'm not sure what the config values were at the time, it does seem like the person in the video is receiving experience based off their experience values before enchanting. Has anyone testing this ruled out this possibility? If not, I'd consider that to be the most likely situation but it would also mean that my hands are tied.

**Comment by CalaMariGold** [comment]
Discovered the issue lies with an incompatibility between Corpse Complex and Clumps. Removing clumps fixes XP dupe on death
