### ISSUE TITLE
Config file for all worlds

### ISSUE THREAD

**Issue by Figgmastah** [TheIllusiveC4/CorpseComplex#66]
I want it so I can set settings for the entire game and not just a world I just made, Like a normal config file.

**Comment by TheIllusiveC4** [comment]
There are no "normal" config files anymore. There are three types: client, common, and server. Corpse Complex has server config files, because they are server-specific. You can set new default configs for new worlds by placing server config files in the `defaultconfigs` folder in the main instance directory.
